"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const groups_controller_1 = require("../controllers/groups.controller");
const router = (0, express_1.Router)();
router.get('/', groups_controller_1.getMany);
router.get('/short', groups_controller_1.getManyShort);
router.get('/:id', groups_controller_1.getOne);
router.put('/:id', groups_controller_1.update);
router.post('/', groups_controller_1.create);
router.delete('/:id', groups_controller_1.deleteOne);
exports.default = router;
