version: '3.8'

services:
  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: employeesMonitoring
    ports:
      - "15432:5432" 
    networks:
      - postgres-compose-network
    volumes:
      - chen_pgdata:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "joaoaoaoj@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - postgres-compose-network
    volumes:
      - chen-pgadmin-data:/var/lib/pgadmin


networks: 
  postgres-compose-network:
    driver: bridge

volumes:
  chen_pgdata:
  chen-pgadmin-data: